# Generated by Django 4.2.2 on 2023-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcionProducto', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=8)),
                ('stock', models.CharField(max_length=3)),
                ('imagen', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
