# Generated by Django 4.2.2 on 2023-06-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password2',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='tienda/uploads/'),
        ),
    ]
